### ISSUE TITLE
Can't add a new Entry

### ISSUE THREAD

**Issue by jwanner83** [liyasthomas/mnmlurl-extension#4]
**Describe the bug**
When I'm trying to add a new URL, the site stays at the "shortening..." message.

**To Reproduce**
1. Go to 'https://mnmlurl.ml/'
2. Add long Link
3. Add alias (optional)
4. Wait and see the error in the console.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/38656104/74665389-edd48800-519f-11ea-891c-7efd51f690e0.png)

**Desktop**
 - OS: Windows 10 Professional
 - Browser: Firefox Developer Edition
 - Version: 74.0b3

**Additional context**
I've had a look at your project dependencies and it looks like jsonstore is currently completly offline and I'm not sure if its coming back any time soon or not.

**Comment by liyasthomas** [comment]
I just tried to reproduce the issue but everything is working as expected. [`jsonstore`](https://www.jsonstore.io/) seems to be up now.

since extensions are not maintained anymore, please consider using web app [mnmlurl.ml](https://mnmlurl.ml/) instead of browser extensions.
